/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UniCommonColor } from "@uiwebkit/common";
import { UniStoreType, UniTabsValue } from "./tabs/models";
export namespace Components {
    interface UniTabs {
        "color": UniCommonColor;
        "feature": string;
        "frame": boolean;
        "mini": boolean;
        "path": string;
        "pathId": string;
        "pro": boolean;
        "selectedIndex": number;
        "shadow": boolean;
        "stacked": boolean;
        "top": boolean;
        "type": UniStoreType;
        "value": string | UniTabsValue;
    }
    interface UniTabsContent {
        "feature": string;
        "path": string;
        "top": boolean;
        "type": UniStoreType;
        "value": string | UniTabsValue;
    }
    interface UniTabsShadow {
        "color": UniCommonColor;
        "feature": string;
        "frame": boolean;
        "mini": boolean;
        "path": string;
        "pathId": string;
        "pro": boolean;
        "selectedIndex": number;
        "stacked": boolean;
        "top": boolean;
        "type": UniStoreType;
        "value": string | UniTabsValue;
    }
}
declare global {
    interface HTMLUniTabsElement extends Components.UniTabs, HTMLStencilElement {
    }
    var HTMLUniTabsElement: {
        prototype: HTMLUniTabsElement;
        new (): HTMLUniTabsElement;
    };
    interface HTMLUniTabsContentElement extends Components.UniTabsContent, HTMLStencilElement {
    }
    var HTMLUniTabsContentElement: {
        prototype: HTMLUniTabsContentElement;
        new (): HTMLUniTabsContentElement;
    };
    interface HTMLUniTabsShadowElement extends Components.UniTabsShadow, HTMLStencilElement {
    }
    var HTMLUniTabsShadowElement: {
        prototype: HTMLUniTabsShadowElement;
        new (): HTMLUniTabsShadowElement;
    };
    interface HTMLElementTagNameMap {
        "uni-tabs": HTMLUniTabsElement;
        "uni-tabs-content": HTMLUniTabsContentElement;
        "uni-tabs-shadow": HTMLUniTabsShadowElement;
    }
}
declare namespace LocalJSX {
    interface UniTabs {
        "color"?: UniCommonColor;
        "feature"?: string;
        "frame"?: boolean;
        "mini"?: boolean;
        "path"?: string;
        "pathId"?: string;
        "pro"?: boolean;
        "selectedIndex"?: number;
        "shadow"?: boolean;
        "stacked"?: boolean;
        "top"?: boolean;
        "type"?: UniStoreType;
        "value"?: string | UniTabsValue;
    }
    interface UniTabsContent {
        "feature"?: string;
        "path"?: string;
        "top"?: boolean;
        "type"?: UniStoreType;
        "value"?: string | UniTabsValue;
    }
    interface UniTabsShadow {
        "color"?: UniCommonColor;
        "feature"?: string;
        "frame"?: boolean;
        "mini"?: boolean;
        "path"?: string;
        "pathId"?: string;
        "pro"?: boolean;
        "selectedIndex"?: number;
        "stacked"?: boolean;
        "top"?: boolean;
        "type"?: UniStoreType;
        "value"?: string | UniTabsValue;
    }
    interface IntrinsicElements {
        "uni-tabs": UniTabs;
        "uni-tabs-content": UniTabsContent;
        "uni-tabs-shadow": UniTabsShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uni-tabs": LocalJSX.UniTabs & JSXBase.HTMLAttributes<HTMLUniTabsElement>;
            "uni-tabs-content": LocalJSX.UniTabsContent & JSXBase.HTMLAttributes<HTMLUniTabsContentElement>;
            "uni-tabs-shadow": LocalJSX.UniTabsShadow & JSXBase.HTMLAttributes<HTMLUniTabsShadowElement>;
        }
    }
}
